name: Testing Workflow Variables

on:
  workflow_dispatch # for manual intervation activate

env:
  cloud: google-cloud #workflow variable

jobs:
  greeting_job:
    runs-on: ubuntu-latest #runner name
    env:
      Greeting: Hello #jobs variable scope is under the job
    steps:
      - name: "Say Hello Mona it's Sunday"
        run: echo "$Greeting $First_Name is using $cloud!"
        env:
          First_Name: Jayanta #step variable scope is inside the step only
